# Generated by Django 4.1 on 2022-08-29 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BestOffers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptions',
            name='text',
        ),
        migrations.AddField(
            model_name='subscriptions',
            name='WAnumber',
            field=models.CharField(default='empty', max_length=20),
        ),
        migrations.AddField(
            model_name='subscriptions',
            name='email',
            field=models.EmailField(default='empty', max_length=1200),
        ),
        migrations.AddField(
            model_name='subscriptions',
            name='ip',
            field=models.CharField(default='empty', max_length=20),
        ),
        migrations.AddField(
            model_name='subscriptions',
            name='name',
            field=models.CharField(default='empty', max_length=200),
        ),
    ]
