# Generated by Django 4.1 on 2022-08-31 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BestOffers', '0002_remove_subscriptions_text_subscriptions_wanumber_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='listings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_date', models.DateTimeField()),
                ('heading', models.CharField(max_length=1200)),
                ('price', models.IntegerField(default=0)),
                ('area', models.IntegerField(default=0)),
                ('rooms', models.IntegerField(default=1)),
                ('location', models.CharField(max_length=200)),
                ('check12', models.CharField(max_length=200)),
                ('link', models.CharField(max_length=1200)),
                ('image', models.CharField(max_length=1200)),
                ('category', models.CharField(max_length=200)),
                ('SubCategory', models.CharField(max_length=200)),
                ('zipcode', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'listings',
            },
        ),
        migrations.DeleteModel(
            name='suggestons',
        ),
    ]
